// Code generated by goctl. DO NOT EDIT.
// Source: study.proto

package server

import (
	"context"

	"github.com/hewenyu/gozero-ent/rpc/internal/logic"
	"github.com/hewenyu/gozero-ent/rpc/internal/svc"
	"github.com/hewenyu/gozero-ent/rpc/pb"
)

type StudyServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStudyServer
}

func NewStudyServer(svcCtx *svc.ServiceContext) *StudyServer {
	return &StudyServer{
		svcCtx: svcCtx,
	}
}

func (s *StudyServer) InitDatabase(ctx context.Context, in *pb.Empty) (*pb.EmptyReply, error) {
	l := logic.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
