// Code generated by goctl. DO NOT EDIT.
// Source: study.proto

package study

import (
	"context"

	"github.com/hewenyu/gozero-ent/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty      = pb.Empty
	EmptyReply = pb.EmptyReply

	Study interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyReply, error)
	}

	defaultStudy struct {
		cli zrpc.Client
	}
)

func NewStudy(cli zrpc.Client) Study {
	return &defaultStudy{
		cli: cli,
	}
}

func (m *defaultStudy) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmptyReply, error) {
	client := pb.NewStudyClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
